version: '3'
services:
  web:
    build: .
    ports:
    -  9191:9191
  db:
    container_name: sample_db
    image: postgres:9.5
    volumes:
    - sample_db:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=docker
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
  ui:
    build:
      context: vm-provisioning-ui/.
      dockerfile: Dockerfile
    environment:
    - NODE_ENV=production
    command: npm start --prefix vm-provisioning-ui/
    ports:
    - 3000:3000
    volumes:
    - .:/app

volumes:
  sample_db: {}